# Generated by Django 6.1 on 2026-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='name_of_category',
        ),
        migrations.AlterField(
            model_name='blogpostsmodel',
            name='category',
            field=models.CharField(choices=[('science and tech', 'science and tech'), ('politics', 'politics'), ('sports', 'sports'), ('infrasture', 'infrasture'), ('finance', 'finance')], max_length=40),
        ),
    ]
