# Generated by Django 6.1 on 2026-08-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_categorymodel_name_of_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
