# Generated by Django 6.1 on 2026-09-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_commentsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostsmodel',
            old_name='tiltle',
            new_name='title',
        ),
    ]
